kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opendatahub-operator
subjects:
- kind: ServiceAccount
  name: opendatahub-operator
  namespace: redhat-ods-operator # Replace it with operator's namespace
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
