kind: ConfigMap
apiVersion: v1
metadata:
  name: rhods-groups-config
  namespace: redhat-ods-applications
  labels:
    app: jupyterhub
    opendatahub.io/modified: 'true'
data:
  admin_groups: rhods-admins
  allowed_groups: 'system:authenticated'